// <auto-generated />
using System;
using BordauxWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BordauxWebApp.Migrations.Bordaux
{
    [DbContext(typeof(BordauxContext))]
    [Migration("20200105193404_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BordauxWebApp.Entities.Act", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Acts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6d6f274-a00d-4428-ad02-ee5144014458"),
                            Name = "Bordaux"
                        },
                        new
                        {
                            Id = new Guid("e7a05533-de1a-4233-bc53-a3bee82acc40"),
                            Name = "Justified"
                        },
                        new
                        {
                            Id = new Guid("7639f454-a6e5-4c04-b10c-5f44cdac09d1"),
                            Name = "DwightLight"
                        });
                });

            modelBuilder.Entity("BordauxWebApp.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("EndDate");

                    b.Property<TimeSpan>("EndTime");

                    b.Property<string>("Name");

                    b.Property<int>("PostalCode");

                    b.Property<string>("PromotorId");

                    b.Property<DateTime>("StartDate");

                    b.Property<TimeSpan>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("PromotorId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76fd0935-62ef-4fc1-ad0f-a88473edc94e"),
                            AddressLine = "Stationsstraat 19",
                            City = "Torhout",
                            DateCreated = new DateTime(2020, 1, 5, 20, 34, 4, 524, DateTimeKind.Local).AddTicks(5992),
                            EndDate = new DateTime(2019, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 4, 0, 0, 0),
                            Name = "2Fish invites Bordaux",
                            PostalCode = 8840,
                            PromotorId = "a11f645a-a580-47c4-87fb-6a57b8e16f68",
                            StartDate = new DateTime(2019, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c453bfbe-bf5a-48fb-9b65-a93fe8aa102d"),
                            AddressLine = "Kuipersstraat 13",
                            City = "Brugge",
                            DateCreated = new DateTime(2020, 1, 5, 20, 34, 4, 526, DateTimeKind.Local).AddTicks(5740),
                            EndDate = new DateTime(2019, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 5, 0, 0, 0),
                            Name = "Club NEO invites Bordaux",
                            PostalCode = 8840,
                            PromotorId = "a11f645a-a580-47c4-87fb-6a57b8e16f68",
                            StartDate = new DateTime(2019, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 23, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("8c092154-95bc-47b2-bb0e-3ac0a34ce097"),
                            AddressLine = "Stationsstraat 10",
                            City = "Torhout",
                            DateCreated = new DateTime(2020, 1, 5, 20, 34, 4, 526, DateTimeKind.Local).AddTicks(5771),
                            EndDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 4, 0, 0, 0),
                            Name = "2Fish invites Bordaux pt 2",
                            PostalCode = 8840,
                            PromotorId = "a11f645a-a580-47c4-87fb-6a57b8e16f68",
                            StartDate = new DateTime(2019, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("BordauxWebApp.Entities.EventAct", b =>
                {
                    b.Property<Guid>("EventId");

                    b.Property<Guid>("ActId");

                    b.HasKey("EventId", "ActId");

                    b.HasIndex("ActId");

                    b.ToTable("EventActs");
                });

            modelBuilder.Entity("BordauxWebApp.Entities.Promotor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Promotors");

                    b.HasData(
                        new
                        {
                            Id = "a11f645a-a580-47c4-87fb-6a57b8e16f68",
                            Email = "robbe.durnez@student.howest.be"
                        });
                });

            modelBuilder.Entity("BordauxWebApp.Entities.Event", b =>
                {
                    b.HasOne("BordauxWebApp.Entities.Promotor", "Promotor")
                        .WithMany("Events")
                        .HasForeignKey("PromotorId");
                });

            modelBuilder.Entity("BordauxWebApp.Entities.EventAct", b =>
                {
                    b.HasOne("BordauxWebApp.Entities.Act", "Act")
                        .WithMany("Events")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BordauxWebApp.Entities.Event", "Event")
                        .WithMany("Acts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
